apiVersion: apps/v1
kind: Deployment
metadata:
    name: matching-coordinator
    labels:
        app: matching-coordinator
spec:
    replicas: 1
    selector:
        matchLabels:
            app: matching-coordinator
    template:
        metadata:
            labels:
                app: matching-coordinator
        spec:
            containers:
                - name: matching-coordinator
                  image: lavorocontainers.azurecr.io/matching-coordinator:<tag>
                  ports:
                      - containerPort: 80
                  env:
                      - name: RABBITMQ_URL
                        valueFrom:
                            secretKeyRef:
                                name: rabbitmq-url
                                key: RABBITMQ_URL
                      - name: DB_CONNECTION_STRING
                        valueFrom:
                            secretKeyRef:
                                name: db-connection-string
                                key: DB_CONNECTION_STRING
