apiVersion: v1
kind: Service
metadata:
    name: matching-coordinator
spec:
    selector:
        app: matching-coordinator
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: LoadBalancer
